import type { AppDatabase, Venture } from '../types/models'

function nowMinus(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()
}

function createVenture(data: Partial<Venture> & Pick<Venture, 'id' | 'ownerId' | 'name' | 'slug'>): Venture {
  return {
    description: '',
    category: 'Otro',
    country: 'Colombia',
    city: 'Bogota',
    socialLinks: {},
    contact: {},
    tags: [],
    status: 'published',
    metrics: {
      profileViews: 0,
      linkClicks: 0,
      followersGiven: 0,
      followersReceived: 0,
      reciprocatedCount: 0,
      favoriteCount: 0,
    },
    reputation: {
      score: 68,
      level: 'active',
      reportCount: 0,
    },
    createdAt: nowMinus(30),
    updatedAt: nowMinus(1),
    ...data,
  }
}

export function createSeedDatabase(): AppDatabase {
  return {
    users: [
      {
        uid: 'demo-viewer',
        email: 'demo@followback.app',
        displayName: 'Demo Founder',
        photoURL: '',
        role: 'user',
        status: 'active',
        onboardingCompleted: false,
        createdAt: nowMinus(2),
        updatedAt: nowMinus(2),
      },
      {
        uid: 'owner-cafe',
        email: 'hola@cafearcana.co',
        displayName: 'Cafe Arcana',
        photoURL: '',
        role: 'user',
        status: 'active',
        onboardingCompleted: true,
        createdAt: nowMinus(90),
        updatedAt: nowMinus(2),
      },
      {
        uid: 'owner-orbita',
        email: 'team@orbita.studio',
        displayName: 'Orbita Studio',
        photoURL: '',
        role: 'user',
        status: 'active',
        onboardingCompleted: true,
        createdAt: nowMinus(120),
        updatedAt: nowMinus(2),
      },
      {
        uid: 'owner-solar',
        email: 'hello@solarbeats.fm',
        displayName: 'Solar Beats',
        photoURL: '',
        role: 'user',
        status: 'active',
        onboardingCompleted: true,
        createdAt: nowMinus(140),
        updatedAt: nowMinus(2),
      },
      {
        uid: 'owner-trazo',
        email: 'info@trazolibre.art',
        displayName: 'Trazo Libre',
        photoURL: '',
        role: 'user',
        status: 'active',
        onboardingCompleted: true,
        createdAt: nowMinus(200),
        updatedAt: nowMinus(2),
      },
    ],
    ventures: [
      createVenture({
        id: 'venture-cafe-arcana',
        ownerId: 'owner-cafe',
        name: 'Cafe Arcana',
        slug: 'cafe-arcana',
        description:
          'Cafe de especialidad con narrativa de marca fuerte, comunidad local y presencia activa en Instagram.',
        category: 'Comida',
        country: 'Colombia',
        city: 'Bogota',
        tags: ['cafe', 'experiencias', 'marca local'],
        socialLinks: {
          instagram: 'https://instagram.com/cafearcana',
          website: 'https://cafearcana.co',
          whatsapp: 'https://wa.me/573001112233',
        },
        metrics: {
          profileViews: 214,
          linkClicks: 88,
          followersGiven: 19,
          followersReceived: 26,
          reciprocatedCount: 15,
          favoriteCount: 12,
        },
        reputation: {
          score: 92,
          level: 'trusted',
          reportCount: 0,
        },
        createdAt: nowMinus(60),
      }),
      createVenture({
        id: 'venture-orbita-studio',
        ownerId: 'owner-orbita',
        name: 'Orbita Studio',
        slug: 'orbita-studio',
        description:
          'Estudio creativo para branding, web y motion design enfocado en emprendimientos digitales.',
        category: 'Diseno',
        country: 'Colombia',
        city: 'Medellin',
        tags: ['branding', 'web', 'motion'],
        socialLinks: {
          instagram: 'https://instagram.com/orbitastudio',
          behance: 'https://behance.net/orbitastudio',
          website: 'https://orbita.studio',
          linkedin: 'https://linkedin.com/company/orbitastudio',
        },
        metrics: {
          profileViews: 176,
          linkClicks: 71,
          followersGiven: 31,
          followersReceived: 20,
          reciprocatedCount: 18,
          favoriteCount: 10,
        },
        reputation: {
          score: 89,
          level: 'trusted',
          reportCount: 0,
        },
        createdAt: nowMinus(82),
      }),
      createVenture({
        id: 'venture-solar-beats',
        ownerId: 'owner-solar',
        name: 'Solar Beats',
        slug: 'solar-beats',
        description:
          'Colectivo musical con lanzamientos en Spotify, visuales para redes y colaboraciones con artistas emergentes.',
        category: 'Musica',
        country: 'Mexico',
        city: 'CDMX',
        tags: ['musica', 'live sessions', 'colaboraciones'],
        socialLinks: {
          instagram: 'https://instagram.com/solarbeats.fm',
          spotify: 'https://open.spotify.com/artist/solarbeats',
          youtube: 'https://youtube.com/@solarbeats',
          x: 'https://x.com/solarbeats',
        },
        metrics: {
          profileViews: 248,
          linkClicks: 119,
          followersGiven: 23,
          followersReceived: 28,
          reciprocatedCount: 17,
          favoriteCount: 18,
        },
        reputation: {
          score: 94,
          level: 'top',
          reportCount: 0,
        },
        createdAt: nowMinus(94),
      }),
      createVenture({
        id: 'venture-trazo-libre',
        ownerId: 'owner-trazo',
        name: 'Trazo Libre',
        slug: 'trazo-libre',
        description:
          'Proyecto artistico de ilustracion y workshops para marcas personales, editoriales y ferias independientes.',
        category: 'Arte',
        country: 'Argentina',
        city: 'Buenos Aires',
        tags: ['ilustracion', 'prints', 'workshops'],
        socialLinks: {
          instagram: 'https://instagram.com/trazolibre.art',
          facebook: 'https://facebook.com/trazolibre.art',
          website: 'https://trazolibre.art',
        },
        metrics: {
          profileViews: 132,
          linkClicks: 44,
          followersGiven: 12,
          followersReceived: 15,
          reciprocatedCount: 9,
          favoriteCount: 6,
        },
        reputation: {
          score: 80,
          level: 'active',
          reportCount: 0,
        },
        createdAt: nowMinus(112),
      }),
    ],
    followActions: [
      {
        id: 'follow-1',
        fromUserId: 'owner-orbita',
        fromVentureId: 'venture-orbita-studio',
        toUserId: 'owner-cafe',
        toVentureId: 'venture-cafe-arcana',
        network: 'instagram',
        status: 'reciprocated',
        createdAt: nowMinus(12),
        updatedAt: nowMinus(10),
      },
      {
        id: 'follow-2',
        fromUserId: 'owner-solar',
        fromVentureId: 'venture-solar-beats',
        toUserId: 'owner-orbita',
        toVentureId: 'venture-orbita-studio',
        network: 'youtube',
        status: 'pending',
        createdAt: nowMinus(4),
        updatedAt: nowMinus(4),
      },
    ],
    favorites: [],
    networkClicks: [],
    analyticsEvents: [],
    reports: [],
  }
}
